# Generated by Django 3.2.7 on 2021-11-27 11:39

import backend.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=backend.settings._default_media_path, verbose_name='Avatar image'),
        ),
    ]
