# Generated by Django 3.2.7 on 2021-11-29 05:43

import backend.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=backend.settings._default_media_path, verbose_name='Avatar image'),
        ),
    ]
