# Generated by Django 3.2.7 on 2021-12-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Major'),
        ),
    ]
