# Generated by Django 3.2.7 on 2021-11-24 03:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('level', models.IntegerField(null=True, verbose_name='Category Level')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('duration', models.TimeField(verbose_name='Duration')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('n_corrects', models.IntegerField(verbose_name='Number of correct answers')),
                ('n_questions', models.IntegerField(verbose_name='Number of question a user took')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Result',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='Code')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.CharField(max_length=255, verbose_name='Content')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None, verbose_name='Answer')),
                ('trueAnswer', models.IntegerField(verbose_name='True answer')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='True answer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Question',
            },
        ),
    ]
