# Generated by Django 3.2.7 on 2021-11-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Category Level'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Score'),
        ),
    ]
