# Generated by Django 3.2.7 on 2021-11-24 03:25

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20211124_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), size=None, verbose_name='Answer'),
        ),
    ]
