# Generated by Django 3.2.7 on 2021-11-24 03:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None, verbose_name='Answer'),
        ),
    ]
