# Generated by Django 3.2.7 on 2021-11-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='NT208', max_length=30, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
