# Generated by Django 3.2.7 on 2021-11-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_delete_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
