# Generated by Django 3.2.7 on 2021-11-27 10:40

from django.db import migrations, models
import backend.settings


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20211127_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to=backend.settings._default_media_path, verbose_name='Image'),
        ),
    ]
