# Generated by Django 3.2.7 on 2021-11-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_result_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='n_questions',
        ),
    ]
