# Generated by Django 3.2.7 on 2021-12-12 07:27

import backend.settings
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_auto_20211130_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=backend.settings._default_media_path, verbose_name='Badge image')),
                ('required_points', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Required points to achieve the badge.')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
    ]
