# Generated by Django 3.2.7 on 2021-09-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('name', models.CharField(max_length=512)),
                ('username', models.CharField(max_length=512)),
                ('password', models.CharField(max_length=512)),
                ('status', models.CharField(max_length=512)),
            ],
        ),
    ]
