# Generated by Django 3.2.7 on 2021-09-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210922_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
